apiVersion: v1
kind: PersistentVolume
metadata:
  name: databases-pv-volume
  namespace: todo-app
  labels:
    type: local
    app: databases
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databases-pv-claim
  namespace: todo-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
